[[language]]
name = "rust"
formatter = { command = "sh", args = ["-c", "leptosfmt --stdin --rustfmt | rustfmt --edition 2024"] }

[language-server.rust-analyzer.config]
cargo.allFeatures = true
procMacro.ignored.leptos_macro = ["server"]
procMacro.enable = true
